### PR TITLE
Add initial flatpak build support

### PR DESCRIPTION
**Pull request by joshua-stone**
This PR adds supports for flatpak as a distribution method. There are numerous advantages of flatpak, such as:

- Normalizing development configuration, as all dependencies are pulled directly from upstream instead of distros
- Providing a reproducible build environment through containerization
- Being a portable packaging format that integrates with different desktops and distros
- Giving developers the freedom to distribute applications over repositories or as bundles. 

It's possible to distribute flatpak'd apps on a centralized repository like [Flathub](https://flathub.org/home), but in the case of MarvInc I think it's best to set it up as a bundle which can be then shipped to itch.io:

```
[jstone@joshua-laptop MarvInc]$ cd dist/flatpak
[jstone@joshua-laptop flatpak]$ ./flatpak-build.sh io.itch.marvellous-inc
[jstone@joshua-laptop flatpak]$ ls -lh io.itch.marvellous-inc.flatpak 
-rw-r--r--. 1 jstone jstone 40M Oct 16 21:45 io.itch.marvellous-inc.flatpak
[jstone@joshua-laptop flatpak]$ flatpak install --user --assumeyes io.itch.marvellous-inc.flatpak
```

Support can be wired up to deploy.sh if there's interest in upstreaming this.

### CODE REVIEW

**Comment by RenatoGeh** [comment]
Thank you for the PR. I like the idea of getting MarvInc to flatpak.

Yeah, my only complaint is `flatpak-build.sh` as a separate script, which you already mentioned. I'll be more than happy to merge this PR if you set this as a `deploy.sh` build flag.

**Comment by joshua-stone** [comment]
@RenatoGeh I've refactored flatpak distribution to be part of deploy.sh. Is there anything else that has to be done?

**Comment by joshua-stone** [comment]
@RenatoGeh @rilifon More commits have been made to improve the flatpak build target. How does everything look now?

**Comment by RenatoGeh** [comment]
LGTM. Tested flatpak build and came out fine. Merging this. Many thanks for the PR.

**Pull request merged**
